namespace APIGenerateUBL.Transversal.Utils
{
    public class ObjectValues
    {
        public static Dictionary<string, string> DiccionarioTipoDeImpuesto = new Dictionary<string, string>()
    {
      { "01", "IVA" },
      { "02", "IC" },
      { "03", "ICA" },
      { "04", "INC" },
      { "05", "ReteIVA" },
      { "06", "ReteRenta" },
      { "07", "ReteICA" },
      { "08", "IC Porcentual" },
      { "20", "FtoHorticultura" },
      { "21", "Timbre" },
      { "22", "INC Bolsas" },
      { "23", "INCarbono" },
      { "24", "INCombustibles" },
      { "25", "Sobretasa Combustibles" },
      { "26", "Sordicom" },
      { "30", "IC Datos" },
      { "ZZ", "Nombre de la figura tributaria" },
      { "ZA", "IVA e INC" },
      { "ZY", "No causa" }
    };


        public static readonly List<Catalogo> CatPaises = new List<Catalogo>
        {
        new Catalogo { key = "AF", value = "Afganistán" },
        new Catalogo { key = "AX", value = "Åland" },
        new Catalogo { key = "AL", value = "Albania" },
        new Catalogo { key = "DE", value = "Alemania" },
        new Catalogo { key = "AD", value = "Andorra" },
        new Catalogo { key = "AO", value = "Angola" },
        new Catalogo { key = "AI", value = "Anguila" },
        new Catalogo { key = "AQ", value = "Antártida" },
        new Catalogo { key = "AG", value = "Antigua y Barbuda" },
        new Catalogo { key = "SA", value = "Arabia Saudita" },
        new Catalogo { key = "DZ", value = "Argelia" },
        new Catalogo { key = "AR", value = "Argentina" },
        new Catalogo { key = "AM", value = "Armenia" },
        new Catalogo { key = "AW", value = "Aruba" },
        new Catalogo { key = "AU", value = "Australia" },
        new Catalogo { key = "AT", value = "Austria" },
        new Catalogo { key = "AZ", value = "Azerbaiyán" },
        new Catalogo { key = "BS", value = "Bahamas" },
        new Catalogo { key = "BD", value = "Bangladés" },
        new Catalogo { key = "BB", value = "Barbados" },
        new Catalogo { key = "BH", value = "Baréin" },
        new Catalogo { key = "BE", value = "Bélgica" },
        new Catalogo { key = "BZ", value = "Belice" },
        new Catalogo { key = "BJ", value = "Benín" },
        new Catalogo { key = "BM", value = "Bermudas" },
        new Catalogo { key = "BY", value = "Bielorrusia" },
        new Catalogo { key = "BO", value = "Bolivia" },
        new Catalogo { key = "BQ", value = "Bonaire, San Eustaquio y Saba" },
        new Catalogo { key = "BA", value = "Bosnia y Herzegovina" },
        new Catalogo { key = "BW", value = "Botsuana" },
        new Catalogo { key = "BR", value = "Brasil" },
        new Catalogo { key = "BN", value = "Brunéi" },
        new Catalogo { key = "BG", value = "Bulgaria" },
        new Catalogo { key = "BF", value = "Burkina Faso" },
        new Catalogo { key = "BI", value = "Burundi" },
        new Catalogo { key = "BT", value = "Bután" },
        new Catalogo { key = "CV", value = "Cabo Verde" },
        new Catalogo { key = "KH", value = "Camboya" },
        new Catalogo { key = "CM", value = "Camerún" },
        new Catalogo { key = "CA", value = "Canadá" },
        new Catalogo { key = "QA", value = "Catar" },
        new Catalogo { key = "TD", value = "Chad" },
        new Catalogo { key = "CL", value = "Chile" },
        new Catalogo { key = "CN", value = "China" },
        new Catalogo { key = "CY", value = "Chipre" },
        new Catalogo { key = "CO", value = "Colombia" },
        new Catalogo { key = "KM", value = "Comoras" },
        new Catalogo { key = "KP", value = "Corea del Norte" },
        new Catalogo { key = "KR", value = "Corea del Sur" },
        new Catalogo { key = "CI", value = "Costa de Marfil" },
        new Catalogo { key = "CR", value = "Costa Rica" },
        new Catalogo { key = "HR", value = "Croacia" },
        new Catalogo { key = "CU", value = "Cuba" },
        new Catalogo { key = "CW", value = "Curazao" },
        new Catalogo { key = "DK", value = "Dinamarca" },
        new Catalogo { key = "DM", value = "Dominica" },
        new Catalogo { key = "EC", value = "Ecuador" },
        new Catalogo { key = "EG", value = "Egipto" },
        new Catalogo { key = "SV", value = "El Salvador" },
        new Catalogo { key = "AE", value = "Emiratos Árabes Unidos" },
        new Catalogo { key = "ER", value = "Eritrea" },
        new Catalogo { key = "SK", value = "Eslovaquia" },
        new Catalogo { key = "SI", value = "Eslovenia" },
        new Catalogo { key = "ES", value = "España" },
        new Catalogo { key = "US", value = "Estados Unidos" },
        new Catalogo { key = "EE", value = "Estonia" },
        new Catalogo { key = "ET", value = "Etiopía" },
        new Catalogo { key = "PH", value = "Filipinas" },
        new Catalogo { key = "FI", value = "Finlandia" },
        new Catalogo { key = "FJ", value = "Fiyi" },
        new Catalogo { key = "FR", value = "Francia" },
        new Catalogo { key = "GA", value = "Gabón" },
        new Catalogo { key = "GM", value = "Gambia" },
        new Catalogo { key = "GE", value = "Georgia" },
        new Catalogo { key = "GH", value = "Ghana" },
        new Catalogo { key = "GI", value = "Gibraltar" },
        new Catalogo { key = "GD", value = "Granada" },
        new Catalogo { key = "GR", value = "Grecia" },
        new Catalogo { key = "GL", value = "Groenlandia" },
        new Catalogo { key = "GP", value = "Guadalupe" },
        new Catalogo { key = "GU", value = "Guam" },
        new Catalogo { key = "GT", value = "Guatemala" },
        new Catalogo { key = "GF", value = "Guayana Francesa" },
        new Catalogo { key = "GG", value = "Guernsey" },
        new Catalogo { key = "GN", value = "Guinea" },
        new Catalogo { key = "GW", value = "Guinea-Bisáu" },
        new Catalogo { key = "GQ", value = "Guinea Ecuatorial" },
        new Catalogo { key = "GY", value = "Guyana" },
        new Catalogo { key = "HT", value = "Haití" },
        new Catalogo { key = "HN", value = "Honduras" },
        new Catalogo { key = "HK", value = "Hong Kong" },
        new Catalogo { key = "HU", value = "Hungría" },
        new Catalogo { key = "IN", value = "India" },
        new Catalogo { key = "ID", value = "Indonesia" },
        new Catalogo { key = "IQ", value = "Irak" },
        new Catalogo { key = "IR", value = "Irán" },
        new Catalogo { key = "IE", value = "Irlanda" },
        new Catalogo { key = "BV", value = "Isla Bouvet" },
        new Catalogo { key = "IM", value = "Isla de Man" },
        new Catalogo { key = "CX", value = "Isla de Navidad" },
        new Catalogo { key = "IS", value = "Islandia" },
        new Catalogo { key = "KY", value = "Islas Caimán" },
        new Catalogo { key = "CC", value = "Islas Cocos" },
        new Catalogo { key = "CK", value = "Islas Cook" },
        new Catalogo { key = "FO", value = "Islas Feroe" },
        new Catalogo { key = "GS", value = "Islas Georgias del Sur y Sandwich del Sur" },
        new Catalogo { key = "HM", value = "Islas Heard y McDonald" },
        new Catalogo { key = "FK", value = "Islas Malvinas" },
        new Catalogo { key = "MP", value = "Islas Marianas del Norte" },
        new Catalogo { key = "MH", value = "Islas Marshall" },
        new Catalogo { key = "PN", value = "Islas Pitcairn" },
        new Catalogo { key = "SB", value = "Islas Salomón" },
        new Catalogo { key = "TC", value = "Islas Turcas y Caicos" },
        new Catalogo { key = "UM", value = "Islas ultramarinas de Estados Unidos" },
        new Catalogo { key = "VG", value = "Islas Vírgenes Británicas" },
        new Catalogo { key = "VI", value = "Islas Vírgenes de los Estados Unidos" },
        new Catalogo { key = "IL", value = "Israel" },
        new Catalogo { key = "IT", value = "Italia" },
        new Catalogo { key = "JM", value = "Jamaica" },
        new Catalogo { key = "JP", value = "Japón" },
        new Catalogo { key = "JE", value = "Jersey" },
        new Catalogo { key = "JO", value = "Jordania" },
        new Catalogo { key = "KZ", value = "Kazajistán" },
        new Catalogo { key = "KE", value = "Kenia" },
        new Catalogo { key = "KG", value = "Kirguistán" },
        new Catalogo { key = "KI", value = "Kiribati" },
        new Catalogo { key = "KW", value = "Kuwait" },
        new Catalogo { key = "LA", value = "Laos" },
        new Catalogo { key = "LS", value = "Lesoto" },
        new Catalogo { key = "LV", value = "Letonia" },
        new Catalogo { key = "LB", value = "Líbano" },
        new Catalogo { key = "LR", value = "Liberia" },
        new Catalogo { key = "LY", value = "Libia" },
        new Catalogo { key = "LI", value = "Liechtenstein" },
        new Catalogo { key = "LT", value = "Lituania" },
        new Catalogo { key = "LU", value = "Luxemburgo" },
        new Catalogo { key = "MO", value = "Macao" },
        new Catalogo { key = "MK", value = "Macedonia" },
        new Catalogo { key = "MG", value = "Madagascar" },
        new Catalogo { key = "MY", value = "Malasia" },
        new Catalogo { key = "MW", value = "Malaui" },
        new Catalogo { key = "MV", value = "Maldivas" },
        new Catalogo { key = "ML", value = "Malí" },
        new Catalogo { key = "MT", value = "Malta" },
        new Catalogo { key = "MA", value = "Marruecos" },
        new Catalogo { key = "MQ", value = "Martinica" },
        new Catalogo { key = "MU", value = "Mauricio" },
        new Catalogo { key = "MR", value = "Mauritania" },
        new Catalogo { key = "YT", value = "Mayotte" },
        new Catalogo { key = "MX", value = "México" },
        new Catalogo { key = "FM", value = "Micronesia" },
        new Catalogo { key = "MD", value = "Moldavia" },
        new Catalogo { key = "MC", value = "Mónaco" },
        new Catalogo { key = "MN", value = "Mongolia" },
        new Catalogo { key = "ME", value = "Montenegro" },
        new Catalogo { key = "MS", value = "Montserrat" },
        new Catalogo { key = "MZ", value = "Mozambique" },
        new Catalogo { key = "MM", value = "Myanmar" },
        new Catalogo { key = "NA", value = "Namibia" },
        new Catalogo { key = "NR", value = "Nauru" },
        new Catalogo { key = "NP", value = "Nepal" },
        new Catalogo { key = "NI", value = "Nicaragua" },
        new Catalogo { key = "NE", value = "Níger" },
        new Catalogo { key = "NG", value = "Nigeria" },
        new Catalogo { key = "UN", value = "Niue" },
        new Catalogo { key = "NF", value = "Norfolk" },
        new Catalogo { key = "NO", value = "Noruega" },
        new Catalogo { key = "NC", value = "Nueva Caledonia" },
        new Catalogo { key = "NZ", value = "Nueva Zelanda" },
        new Catalogo { key = "OM", value = "Omán" },
        new Catalogo { key = "NL", value = "Países Bajos" },
        new Catalogo { key = "PK", value = "Pakistán" },
        new Catalogo { key = "PW", value = "Palaos" },
        new Catalogo { key = "PS", value = "Palestina" },
        new Catalogo { key = "PA", value = "Panamá" },
        new Catalogo { key = "PG", value = "Papúa Nueva Guinea" },
        new Catalogo { key = "PY", value = "Paraguay" },
        new Catalogo { key = "PE", value = "Perú" },
        new Catalogo { key = "PF", value = "Polinesia Francesa" },
        new Catalogo { key = "PL", value = "Polonia" },
        new Catalogo { key = "PT", value = "Portugal" },
        new Catalogo { key = "PR", value = "Puerto Rico" },
        new Catalogo { key = "GB", value = "Reino Unido" },
        new Catalogo { key = "EH", value = "República Árabe Saharaui Democrática" },
        new Catalogo { key = "CF", value = "República Centroafricana" },
        new Catalogo { key = "CZ", value = "República Checa" },
        new Catalogo { key = "CG", value = "República del Congo" },
        new Catalogo { key = "CD", value = "República Democrática del Congo" },
        new Catalogo { key = "DO", value = "República Dominicana" },
        new Catalogo { key = "RE", value = "Reunión" },
        new Catalogo { key = "RW", value = "Ruanda" },
        new Catalogo { key = "RO", value = "Rumania" },
        new Catalogo { key = "RU", value = "Rusia" },
        new Catalogo { key = "WS", value = "Samoa" },
        new Catalogo { key = "AS", value = "Samoa Americana" },
        new Catalogo { key = "BL", value = "San Bartolomé" },
        new Catalogo { key = "KN", value = "San Cristóbal y Nieves" },
        new Catalogo { key = "SM", value = "San Marino" },
        new Catalogo { key = "MF", value = "San Martín" },
        new Catalogo { key = "PM", value = "San Pedro y Miquelón" },
        new Catalogo { key = "VC", value = "San Vicente y las Granadinas" },
        new Catalogo { key = "SH", value = "Santa Elena, Ascensión y Tristán de Acuña" },
        new Catalogo { key = "LC", value = "Santa Lucía" },
        new Catalogo { key = "ST", value = "Santo Tomé y Príncipe" },
        new Catalogo { key = "SN", value = "Senegal" },
        new Catalogo { key = "RS", value = "Serbia" },
        new Catalogo { key = "SC", value = "Seychelles" },
        new Catalogo { key = "SL", value = "Sierra Leona" },
        new Catalogo { key = "SG", value = "Singapur" },
        new Catalogo { key = "SX", value = "Sint Maarten" },
        new Catalogo { key = "SY", value = "Siria" },
        new Catalogo { key = "SO", value = "Somalia" },
        new Catalogo { key = "LK", value = "Sri Lanka" },
        new Catalogo { key = "SZ", value = "Suazilandia" },
        new Catalogo { key = "ZA", value = "Sudáfrica" },
        new Catalogo { key = "SD", value = "Sudán" },
        new Catalogo { key = "SS", value = "Sudán del Sur" },
        new Catalogo { key = "SI", value = "Suecia" },
        new Catalogo { key = "CH", value = "Suiza" },
        new Catalogo { key = "SR", value = "Surinam" },
        new Catalogo { key = "SJ", value = "Svalbard y Jan Mayen" },
        new Catalogo { key = "TH", value = "Tailandia" },
        new Catalogo { key = "TW", value = "Taiwán (República de China)" },
        new Catalogo { key = "TZ", value = "Tanzania" },
        new Catalogo { key = "TJ", value = "Tayikistán" },
        new Catalogo { key = "IO", value = "Territorio Británico del Océano Índico" },
        new Catalogo { key = "TF", value = "Tierras Australes y Antárticas Francesas" },
        new Catalogo { key = "TL", value = "Timor Oriental" },
        new Catalogo { key = "TG", value = "Togo" },
        new Catalogo { key = "TK", value = "Tokelau" },
        new Catalogo { key = "TO", value = "Tonga" },
        new Catalogo { key = "TT", value = "Trinidad y Tobago" },
        new Catalogo { key = "TN", value = "Túnez" },
        new Catalogo { key = "TM", value = "Turkmenistán" },
        new Catalogo { key = "TR", value = "Turquía" },
        new Catalogo { key = "TV", value = "Tuvalu" },
        new Catalogo { key = "UA", value = "Ucrania" },
        new Catalogo { key = "UG", value = "Uganda" },
        new Catalogo { key = "UY", value = "Uruguay" },
        new Catalogo { key = "UZ", value = "Uzbekistán" },
        new Catalogo { key = "VU", value = "Vanuatu" },
        new Catalogo { key = "VA", value = "Vaticano, Ciudad del" },
        new Catalogo { key = "VE", value = "Venezuela" },
        new Catalogo { key = "VN", value = "Vietnam" },
        new Catalogo { key = "WF", value = "Wallis y Futuna" },
        new Catalogo { key = "YE", value = "Yemen" },
        new Catalogo { key = "DJ", value = "Yibuti" },
        new Catalogo { key = "ZM", value = "Zambia" },
        new Catalogo { key = "ZW", value = "Zimbabue" },
        };
    }

    public partial class Catalogo
    {
        public String key { get; set; }

        public String value { get; set; }

        public static String GetValue(String Key, List<Catalogo> catalogo)
        {
            String value = "";

            Catalogo? result = catalogo.Where(k => k.key == Key).FirstOrDefault();
            if (result != null)
                value = result.value;

            return value;
        }
    }
}
